### ISSUE TITLE
в моделях наследниках переписаны методы модели родителя

### ISSUE THREAD

**Issue by cjbars** [7yon/Web-developing.Backend#1]
Если вы не меняете функционал в модели наследнике, то не и не стоит переопределять методы родительской модели.
Так во всех моделях вы реализовали(скопипастили) методы load...save и т.д.  
Зачем?

**Comment by 7yon** [comment]
ya sdelal' 369e84da9dcac9943ae87adecba0dd1e38ffb9f1
